using QuantDesk.Domain.Contracts;
using QuantDesk.Runtime.Research;

namespace QuantDesk.Runtime.Tests.Research;

/// <summary>
/// Reads the same published bundle the Python side reads, from one shared fixture.
///
/// The other reader tests use hand-written JSON literals. Those verify the reader against an
/// opinion about the contract rather than against the producer, so they cannot catch drift — and
/// drift has already happened once here: a manifest loader was switched to camelCase while every
/// committed manifest was snake_case, and nothing noticed until the equity research could no
/// longer open its own datasets.
///
/// This pins both languages to one artifact generated by the Python contract types. If the
/// publisher changes shape, this test fails on the C# side rather than a runtime deserialisation
/// failing in production.
/// </summary>
public sealed class CrossLanguageContractFixtureTests
{
    private static readonly string FixtureRoot = LocateFixtures();

    [Fact]
    public void TheFixtureDirectoryIsPresent() =>
        Assert.True(
            Directory.Exists(FixtureRoot),
            $"Expected the shared cross-language fixture at {FixtureRoot}. " +
            "It is regenerated by research/python tests/unit/test_cross_language_contract_fixture.py.");

    [Fact]
    public void ThePublishedFeatureSchemaIsReadable()
    {
        FeatureSchemaContract schema = PythonResearchContractReader.ReadFeatureSchema(
            Read("feature-schema.json"));

        Assert.Equal("deterministic-rule-v1", schema.SchemaVersion);
        Assert.NotEmpty(schema.FeatureNames);
        Assert.False(string.IsNullOrWhiteSpace(schema.FeatureHash));
    }

    [Fact]
    public void ThePublishedModelArtifactIsReadable()
    {
        ModelArtifactContract artifact = PythonResearchContractReader.ReadModelArtifact(
            Read("model-artifact.json"));

        Assert.False(string.IsNullOrWhiteSpace(artifact.ArtifactId));
        Assert.Equal("donchian_breakout", artifact.StrategyFamily);
        Assert.Equal("BTC/USD", artifact.StrategyDefinition.Symbol);
        // Every required gate must arrive as real evidence, not a bare pass flag.
        Assert.Contains("R0", artifact.ValidationGates);
        Assert.Contains("R12", artifact.ValidationGates);
    }

    [Fact]
    public void ThePublishedForecastIsReadable()
    {
        ForecastSnapshotContract forecast = PythonResearchContractReader.ReadForecast(
            Read("forecast-snapshot.json"));

        Assert.Equal("BTC/USD", forecast.Instrument);
        Assert.Equal("directional_return_bps", forecast.ForecastFamily);
        Assert.Equal(42.0m, forecast.PointForecast);
    }

    [Fact]
    public void ThePublishedBundleValidatesAsOneCoherentSet()
    {
        FeatureSchemaContract schema = PythonResearchContractReader.ReadFeatureSchema(
            Read("feature-schema.json"));
        ModelArtifactContract artifact = PythonResearchContractReader.ReadModelArtifact(
            Read("model-artifact.json"));
        ForecastSnapshotContract forecast = PythonResearchContractReader.ReadForecast(
            Read("forecast-snapshot.json"));

        // This is the check that matters: the three documents must agree with each other, not
        // merely parse individually.
        PythonResearchContractReader.ValidateForecast(artifact, schema, forecast);
    }

    [Fact]
    public void AForecastBoundToADifferentArtifactIsRejected()
    {
        FeatureSchemaContract schema = PythonResearchContractReader.ReadFeatureSchema(
            Read("feature-schema.json"));
        ModelArtifactContract artifact = PythonResearchContractReader.ReadModelArtifact(
            Read("model-artifact.json"));
        ForecastSnapshotContract forecast = PythonResearchContractReader.ReadForecast(
            Read("forecast-snapshot.json").Replace(
                artifact.ArtifactHash, new string('e', 64), StringComparison.Ordinal));

        // A rebuilt artifact must not be silently substitutable for the one that was validated.
        Assert.ThrowsAny<Exception>(
            () => PythonResearchContractReader.ValidateForecast(artifact, schema, forecast));
    }

    [Fact]
    public void ThePublishedForecastCarriesItsOwnUncertaintyAcrossTheLanguageBoundary()
    {
        // The channel existed on the wire as an untyped, always-null "prediction_interval", and the
        // C# reader dropped it along with "confidence". So the one number that could have said how
        // wrong a forecast might be was neither published nor read, and a point estimate was traded
        // as though it were exact.
        ForecastSnapshotContract forecast = PythonResearchContractReader.ReadForecast(
            Read("forecast-snapshot.json"));

        Assert.NotNull(forecast.Uncertainty);
        Assert.Equal(8.0, forecast.Uncertainty.StandardErrorBps);
        Assert.Equal(12.5, forecast.Uncertainty.HistoricalNetEdgeBps);
        Assert.Equal(412, forecast.Uncertainty.HistoricalObservations);
    }

    [Fact]
    public void AForecastWithoutAnUncertaintyBlockStillReadsButSaysNothingAboutItsError()
    {
        // Backward compatible on the wire, and refused at the gate. Reading is not the same as
        // trusting: an older publisher can still be parsed, and the assessment declines to trade it.
        string withoutUncertainty = Read("forecast-snapshot.json")
            .Replace("\"uncertainty\"", "\"unused_uncertainty\"", StringComparison.Ordinal);

        Assert.Null(PythonResearchContractReader.ReadForecast(withoutUncertainty).Uncertainty);
    }

    [Fact]
    public void AMalformedUncertaintyBlockIsAnErrorRatherThanASilentNull()
    {
        // Degrading a broken block to "unstated" would let a publishing bug quietly reopen the gap.
        string broken = Read("forecast-snapshot.json")
            .Replace("\"standard_error_bps\": 8.0", "\"standard_error_bps\": \"eight\"", StringComparison.Ordinal);

        Assert.Throws<InvalidDataException>(() => PythonResearchContractReader.ReadForecast(broken));
    }

    private static string Read(string name) => File.ReadAllText(Path.Combine(FixtureRoot, name));

    /// <summary>Walks up from the test binary to the repository root.</summary>
    private static string LocateFixtures()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !Directory.Exists(Path.Combine(directory.FullName, ".git")))
            directory = directory.Parent;
        return Path.Combine(
            directory?.FullName ?? AppContext.BaseDirectory,
            "tests", "fixtures", "research-contracts");
    }
}
