<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\QuantDesk.Alpaca\QuantDesk.Alpaca.csproj" />
    <ProjectReference Include="..\QuantDesk.Domain\QuantDesk.Domain.csproj" />
    <ProjectReference Include="..\QuantDesk.Runtime\QuantDesk.Runtime.csproj" />
  </ItemGroup>
</Project>

